In [1]:
from sklearn import datasets

In [2]:
diabetes_data = datasets.load_diabetes()

In [3]:
diabetes_data.keys()

dict_keys(['data', 'target', 'DESCR', 'feature_names', 'data_filename', 'target_filename'])

In [4]:
diabetes_features = diabetes_data['data']
diabetes_features[0:5]

array([[ 0.03807591,  0.05068012,  0.06169621,  0.02187235, -0.0442235 ,
        -0.03482076, -0.04340085, -0.00259226,  0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, -0.02632783, -0.00844872,
        -0.01916334,  0.07441156, -0.03949338, -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, -0.00567061, -0.04559945,
        -0.03419447, -0.03235593, -0.00259226,  0.00286377, -0.02593034],
       [-0.08906294, -0.04464164, -0.01159501, -0.03665645,  0.01219057,
         0.02499059, -0.03603757,  0.03430886,  0.02269202, -0.00936191],
       [ 0.00538306, -0.04464164, -0.03638469,  0.02187235,  0.00393485,
         0.01559614,  0.00814208, -0.00259226, -0.03199144, -0.04664087]])

In [6]:
diabetes_target = diabetes_data['target']
diabetes_target[0:5]

array([151.,  75., 141., 206., 135.])

In [7]:
from sklearn.model_selection import train_test_split

In [9]:
X_train,X_test,y_train,y_test = train_test_split(diabetes_features,diabetes_target,test_size=0.3,random_state=42)
len(X_train),len(y_train),len(X_test),len(y_test)

(309, 309, 133, 133)

In [12]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
import numpy as np

In [20]:
diabetes_model = KNeighborsClassifier()
param_grid={'weights':['uniform','distance'],
           'algorithm':['ball_tree','kd_tree','brute'],
           'n_neighbors':[3,5,7,9]}

In [21]:
grid_model = GridSearchCV(diabetes_model,param_grid,cv=3)

In [22]:
knngrid=grid_model.fit(X_train,y_train)

C:\Users\Ganesh\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:652: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)
C:\Users\Ganesh\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [24]:
knngrid.best_score_

0.012944983818770227

In [25]:
knngrid.best_estimator_

KNeighborsClassifier(algorithm='ball_tree', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='distance')

In [27]:
knn_best = knngrid.best_estimator_

In [37]:
y_pred=knn_best.predict(X_test)

In [38]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.015037593984962405

In [39]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [40]:
from sklearn.metrics import classification_report
classification_report(y_test,y_pred)

C:\Users\Ganesh\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Ganesh\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


'              precision    recall  f1-score   support\n\n        25.0       0.00      0.00      0.00         0\n        37.0       0.00      0.00      0.00         1\n        42.0       0.00      0.00      0.00         1\n        47.0       0.00      0.00      0.00         0\n        48.0       0.00      0.00      0.00         2\n        49.0       0.00      0.00      0.00         0\n        51.0       0.00      0.00      0.00         0\n        52.0       0.00      0.00      0.00         3\n        53.0       0.00      0.00      0.00         1\n        55.0       0.00      0.00      0.00         0\n        58.0       0.00      0.00      0.00         0\n        59.0       0.25      1.00      0.40         1\n        60.0       0.00      0.00      0.00         2\n        61.0       0.00      0.00      0.00         2\n        63.0       0.00      0.00      0.00         3\n        64.0       0.00      0.00      0.00         1\n        65.0       0.00      0.00      0.00         1\n       