In [1]:
#import numpy
import numpy as np

In [2]:
#Numpy array is a homogenous array, and can be created from lists and tutples as below
listNumpyArray = np.array([1,2,3])
tupleNumpyArray = np.array((4,5,6))

In [3]:
listNumpyArray

array([1, 2, 3])

In [4]:
tupleNumpyArray

array([4, 5, 6])

In [5]:
#creating numpy array with free text of any datatype gives error
freeTextArray = np.array(1,2,3)

ValueError: only 2 non-keyword arguments accepted

In [6]:
#creating numpy array with heterogenous data 
hetrgnsArray = np.array([1,'w',1.3])

In [7]:
hetrgnsArray

array(['1', 'w', '1.3'], dtype='<U11')

In [8]:
# all the heterogenous data is converted into strings and converted into numpy array, as different datatypes are not allowed in one array

In [9]:
hetrgnNumArray = np.array([1,2.3])

In [10]:
hetrgnNumArray

array([1. , 2.3])

In [11]:
#In the above array, the data is converted into floats

In [13]:
#create multidimensional array from list
mdNumpyArrayList = np.array([[1,2,3],[4,5,6]])
mdNumpyArrayList

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
#create multidimensional array from tuple of lists
mdNumpyArrayTuple = np.array(([1,2,3],[4,5,6]))
mdNumpyArrayTuple

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
#create multidimensional array from tuple of tuples
mdNumpyArrayListTup = np.array(((1,2,3),(4,5,6)))
mdNumpyArrayListTup

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
#Basic properties of numpy array, I'm considering mdNumpyArrayListTup for example: The result is 2 rows and 3 columns.
mdNumpyArrayListTup.shape

(2, 3)

In [21]:
#returns number of dimensions
mdNumpyArrayListTup.ndim

2

In [23]:
#returns datatypes of array
mdNumpyArrayListTup.dtype

dtype('int32')

In [24]:
#returns size of array
mdNumpyArrayListTup.size

6

In [26]:
#returns item size (number of bytes) of the elements in array, it is determined by the datatype of the elements.
mdNumpyArrayListTup.itemsize

4

In [27]:
#creating an array with given dimensions using arange function
#arange returns numpy array whereas range function in python returns list, 
#arange is preferred in case if the speed is important, we can also metion start and stop boundaries along with step.
#reshape shapes the array into given dimensions
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
#If there are any scenarios where the shape of the array is known but the elements are unknown, we can use the below functions for such scenarios
print(np.zeros((3,5)))
print(np.ones((3,5)))
print(np.empty((3,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [33]:
#When arange is used with floating point numbers, it is not possible to obtain the number of elements because of the finite floating point precision
#as an alternative to this linspace is used, it takes the number of elements as a parameter along with start and stop.
np.linspace(0,0.5,10)

array([0.        , 0.05555556, 0.11111111, 0.16666667, 0.22222222,
       0.27777778, 0.33333333, 0.38888889, 0.44444444, 0.5       ])

In [34]:
#One of the main flexibilities with numpy arrays is to perform mathematical operations easily, some of the operations are illustrated below
arg1 = np.array([1,2,3])
print(arg1+2)

[3 4 5]


In [35]:
print(arg1-1)

[0 1 2]


In [36]:
print(arg1*3)

[3 6 9]


In [37]:
print(arg1**2)

[1 4 9]


In [38]:
print(arg1/2)

[0.5 1.  1.5]


In [39]:
print(arg1%2)

[1 0 1]


In [40]:
#we can even perform trigonometric operations
print(np.sin(arg1))

[0.84147098 0.90929743 0.14112001]


In [41]:
trigArg = np.array([0,90,180])
print(np.cos(trigArg))

[ 1.         -0.44807362 -0.59846007]


In [42]:
#we can also check <,> and == operations
print(arg1<5)

[ True  True  True]


In [43]:
print(arg1==1)

[ True False False]


In [44]:
#matrix operations
m1 = np.eye(2)
m1


array([[1., 0.],
       [0., 1.]])

In [45]:
m2 = np.array([[2,3],[4,5]])
m2

array([[2, 3],
       [4, 5]])

In [46]:
#performs straight product
m1*m2

array([[2., 0.],
       [0., 5.]])

In [47]:
#performs matrix multiplication
m1.dot(m2)

array([[2., 3.],
       [4., 5.]])

In [48]:
print(m2-m1)

[[1. 3.]
 [4. 4.]]


In [52]:
#if we want to modify the existing array without using any temp array, we shul use +=, *=,-+ etc
m1 += m2
print(m2)
print(m1)

[[2 3]
 [4 5]]
[[3. 3.]
 [4. 6.]]


In [53]:
#if we try to reverse the operation, it will throw an error as the operand can be upcasted but not downcasted
m2+=m1

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [56]:
#unary operations 
m1.sum()

16.0

In [57]:
m1.sum(0) # sum along column

array([7., 9.])

In [58]:
m1.sum(1) # sum along rows

array([ 6., 10.])

In [64]:
#random number generator in numpy
np.random.random_integers(10,20,size=(2,5))

C:\Users\Ganesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: This function is deprecated. Please call randint(10, 20 + 1) instead
  


array([[13, 10, 10, 15, 15],
       [13, 14, 19, 20, 14]])

In [65]:
np.random.random_integers(10,20,size=(2,5))

C:\Users\Ganesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(10, 20 + 1) instead
  """Entry point for launching an IPython kernel.


array([[13, 13, 11, 20, 10],
       [19, 14, 19, 16, 15]])

In [67]:
#when we observe the above two outputs, it is evident that the outputs generated by the two random methods are different
#hence seed needs to be used in order to get same output every time
np.random.seed(10)
np.random.random_integers(10,20,size=(2,5))

C:\Users\Ganesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: This function is deprecated. Please call randint(10, 20 + 1) instead
  after removing the cwd from sys.path.


array([[19, 14, 10, 11, 19],
       [10, 11, 20, 18, 19]])

In [69]:
np.random.seed(10)
np.random.random_integers(10,20,size=(2,5))

C:\Users\Ganesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: This function is deprecated. Please call randint(10, 20 + 1) instead
  


array([[19, 14, 10, 11, 19],
       [10, 11, 20, 18, 19]])

In [70]:
#Both the above cells have same seed, hence returns same numpy array
#arrayName[rownum,column num]

In [73]:
#Slicing the numpy array
a = np.array([[1,2,3,4],[5,6,7,8]])
a[0,1]

2

In [74]:
a[0:2,1]

array([2, 6])

In [75]:
a[1,1:3]

array([6, 7])

In [76]:
#mean,median,mode,std,variance

In [77]:
#mean for all elements in the matrix
a.mean()

4.5

In [78]:
#mean for elements in column
a.mean(0)

array([3., 4., 5., 6.])

In [79]:
#mean for elements in row
a.mean(1)

array([2.5, 6.5])

In [ ]:
#we can also use np.mean() method instead of applying it directly on the numpy array

In [88]:
#median of all elements in a
np.median(a)

4.5

In [89]:
#median of all elements in the columns
np.median(a,0)

array([3., 4., 5., 6.])

In [90]:
#median of all elements in a row
np.median(a,1)

array([2.5, 6.5])

In [91]:
#similar case with standard deviation and variance
np.std(a)

2.29128784747792

In [93]:
np.var(a)

5.25

In [94]:
#Iterating over the numpy array
for row in a:
    print(row)

[1 2 3 4]
[5 6 7 8]


In [96]:
#in case we have to perfrom any operations on all the elemnts of an arraythen we use flat
for z in a.flat:
    print(z**2)

1
4
9
16
25
36
49
64


In [104]:
#Stacking the arrays can be in horizontal or vertical direction
b=np.array([[5,8,9,10],[23,34,45,56]])

In [105]:
np.hstack((a,b))

array([[ 1,  2,  3,  4,  5,  8,  9, 10],
       [ 5,  6,  7,  8, 23, 34, 45, 56]])

In [106]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 5,  8,  9, 10],
       [23, 34, 45, 56]])

In [107]:
c=np.array([23,34,45,56])

In [109]:
np.vstack((a,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [23, 34, 45, 56]])

In [111]:
#we can also split the matrix
#along columns
np.hsplit(a,2)

[array([[1, 2],
        [5, 6]]), array([[3, 4],
        [7, 8]])]

In [112]:
#along rows
np.vsplit(a,2)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [114]:
#Numpy arrays are mutable and works based on references
#no copy, no new memory location created
a1 = np.array([1,2,3,4])
b1=a1
a1[0]=5
b1

array([5, 2, 3, 4])

In [ ]:
#shallow copy

In [115]:
#deep copy, memory location allotted
b1=a1.copy()
a1[0]=10
b1

array([5, 2, 3, 4])

In [117]:
#broadcasting
#this concept is used when we have to perform matrix operation between two matrices which doesnt accept the dimenionality conditions
#The two rules followed are 
#1. THe smaller array will be appended with 1's until it reaches the size of the larger array
#2. The array wth dimension 1 will be assumed to have the dimension of the largest array in that axis
a2=np.array([1,2,3,4])
a3=np.array([5,6,7])
(a2+a3).shape

ValueError: operands could not be broadcast together with shapes (4,) (3,) 